version: '3.3'

services:
  redis:
    build: ./backend/redis
    restart: unless-stopped
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6379"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  database:
    build: ./backend/database
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ls
      - POSTGRES_PASSWORD=ls
      - POSTGRES_DB=ls
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 30s
      timeout: 10s
      retries: 5
    
  server:
    build:
      context: .  
      dockerfile: ./backend/server/Dockerfile
    restart: unless-stopped
    depends_on:
      - database
      - redis
    network_mode: host

  spa:
    build:
      context: .  
      dockerfile: ./frontend/Dockerfile
    restart: unless-stopped
    depends_on:
      - database
      - redis
    network_mode: host
