version: '3.3'

services:
  redis:
    build: ./backend/redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - /redis-data:/data
  
  database:
    build: ./backend/database
    restart: unless-stopped
    volumes:
      - /postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ls
      - POSTGRES_PASSWORD=ls
      - POSTGRES_DB=ls
    
  server:
    build:
      context: .  
      dockerfile: ./backend/server/Dockerfile
    restart: unless-stopped
    depends_on:
      - database
      - redis
    network_mode: host
    volumes:
      - /server-data:/repositories

  spa:
    build:
      context: .  
      dockerfile: ./frontend/Dockerfile
    restart: unless-stopped
    depends_on:
      - database
      - redis
    network_mode: host
